### PR TITLE
[Merged by Bors] - fix: manually link libduckdb for linux

### PR DESCRIPTION
**Pull request by nacardin**

### CODE REVIEW

**Comment by AlexMikhalev** [comment]
works on mac m2.

**Comment by sehz** [comment]
This is the new DuckDB extension template CMake.  https://github.com/duckdb/extension-template/blob/main/CMakeLists.txt.
@AlexMikhalev Can you test it out if that works on Linux?.  If so  we should converge on it.

**Review by sehz — APPROVED** [review]
works

**Pull request closed without merging**
